# Лабораторная работа 1. Введение в машинное обучение. Обучение с учителем. Задача регрессии

<b>Традиционное предупреждение для всех лабораторных работ:</b> перед обучением моделей необходимо выполнить предварительную обработку данных, которая <b>обязательно</b> включает в себя:
- заполнение пропущенных значений (рекомедуется логика заполнения пропусков на основе типа данных, которая использовалась в РГР по Практикуму);
- преобразование категориальных признаков в числовые (используйте one-hot кодирование или map; используйте знания с Практикума).

Предобработка может включать в себя другие действия, но выполнение описанных выше действий обязательно.

Сделайте это один раз и сохраните в отдельный csv файл, а потом его используйте.

<b>Выполните следующие задания:</b>
- загрузите датасет для регрессии, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (линейная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (полиномиальная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- вычислите значения метрик $R^2$, MAE, MSE, RMSE, MAPE для всех обученных моделей; выберите лучшую модель;
- самостоятельно реализуйте (желательно в виде класса) модель линейной регрессии с регуляризацией (можете выбрать L1 или L2);
- самостоятельно реализуйте вычисление всех используемых метрик (в виде функций, принимающих два аргумента);
- обучите вашу модель линейной регрессии на ваших данных; оцените качество с помощью реализованных вами метрик.

In [21]:
# пишите код здесь и в ячейках ниже
import pandas as pd
import numpy as np

#df = pd.read_csv('..\data\cars.csv')

#df.info()
#df.describe()

#df = df.replace({ True : 1 , False : 0 })

#s=pd.get_dummies(df)
#s.to_csv('..\data\one-hot_encoded_cars.csv', index=False)


#Проверка датасета на пустые значения

#missing_data = df.isnull()
#for column in missing_data.columns.values.tolist():
#    print(column)
#    print(missing_data[column].value_counts())
#    print(" ")
#df.isnull().sum()    
#df.info()


#Замена NaN значений в столбце объема двигателя

#vnn = df['engine_capacity'].dropna()
#df['engine_capacity'] = df['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))



"""
df = pd.read_csv('..\data\one-hot_encoded_cars.csv')

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X
"""




#Датасет предобработан: значения False/True заменены на 0/1;
#Выполнено one-hot кодирование; пустые значения в датафрейме заменены;
#Выделены целевой признак и предикторы


'\ndf = pd.read_csv(\'..\\data\\one-hot_encoded_cars.csv\')\n\ny = df["price_usd"]\nX = df.drop(["price_usd"], axis=1)\nX\n'

In [22]:
"""
ddf = pd.read_csv('..\data\cars.csv')
xxx = ddf.drop(columns = 'color')
xxx['longtitude']=np.zeros(38531)
xxx['latitude']=np.zeros(38531)
towndata = {
'мнд': np.float64(27.56152), 'мнш': np.float64(53.90454),
'год': np.float64(30.98785), 'гош': np.float64(52.44118),
'бд': np.float64(23.73405), 'бш': np.float64(52.09762),
'мд': np.float64(30.33136), 'мш': np.float64(53.90072),
'вд': np.float64(30.20162), 'вш': np.float64(55.18481),
'гд': np.float64(23.81313), 'гш': np.float64(53.66935)

}

#print(towndata["Миснк"][1])
for i in xxx['drivetrain']:
    if i == "front":
        i = int(0)
    if i == "rear":
        i = int(1)
    if i == "all":
        i = int(2)
print(xxx['location_region'].unique())
for i in range(len(xxx['location_region'])):
    
    #print(xxx['location_region'][i])
    
    if xxx['location_region'][i]=='Минская обл.':
        xxx['longtitude'][i]=towndata['мнд']
        xxx['latitude'][i]=towndata['мнш']
        
    if xxx['location_region'][i]=='Гомельская обл.':
        xxx['longtitude'][i]=towndata['год']
        xxx['latitude'][i]=towndata['гош']
        
    if xxx['location_region'][i]=='Брестская обл.':
        xxx['longtitude'][i]=towndata['бд']
        xxx['latitude'][i]=towndata['бш']
        
    if xxx['location_region'][i]=='Могилевская обл.':
        xxx['longtitude'][i]=towndata['мд']
        xxx['latitude'][i]=towndata['мш']
        
    if xxx['location_region'][i]=='Витебская обл.':
        xxx['longtitude'][i]=towndata['вд']
        xxx['latitude'][i]=towndata['вш']
        
    if xxx['location_region'][i]=='Гродненская обл.':
        xxx['longtitude'][i]=towndata['гд']
        xxx['latitude'][i]=towndata['гш']

#for i in range(len(xxx['location_region'])):
    #print(xxx['location_region'][i], xxx['latitude'][i], xxx['longtitude'][i])
xxx.info()




xxx = xxx.drop(columns = "location_region")
vnn = xxx['engine_capacity'].dropna()
xxx['engine_capacity'] = xxx['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))
xxx = xxx.replace({ True : 1 , False : 0 })
xxx = xxx.drop(columns = "model_name")
s=pd.get_dummies(xxx)
s.to_csv('..\data\workinset.csv', index=False)

"""
# False/True replaced with 0/1
# drivetrain replaced with 0/1/2 (front/rear/awd)
# region_location object type column replaced with two float64 type columns longtitude, lattitude
# color obj type column was dropped for less mem usage

# hope im not going to drop model or manufacturer column due to mem error :blessrng:

# model_name column was dropped :// saved 1100 columns
# other data was one-hot encoded


#df = pd.read_csv('..\data\one-hot_encoded_cars.csv')
df = pd.read_csv('..\data\workinset.csv')

"""ddf = pd.read_csv('..\data\cars.csv')
df["model_name"] = ddf["model_name"]
#print(*ddf['manufacturer_name'].unique())
print()
print()
#print(*df['model_name'].unique())
"""
"""foruniques['manufacturer_name'] = ddf['manufacturer_name']
foruniques['model_name']=df['model_name']
foruniques
"""

"""#print(*df['model_name'].unique())

ucars={}

uniquesm=df['model_name'].unique()
for i in range(len(uniquesm)):
    counter = 0
    
    for j in ddf['model_name']:
        
        #print(counter)
        if counter < 38533:
            #print(counter)
            if uniquesm[i]==j:
                #print(ddf['manufacturer_name'][counter], j)
                ucars[str(ddf['manufacturer_name'][counter] + ' ' + j)] = "Z"
                #print()
                #print()
                #print("promres", ucars)
        counter+=1
        
        
        
print("EXECUTED!!!")

import pickle 

with open('saved_dictionary.pkl', 'wb') as f:
    pickle.dump(ucars, f)
        
with open('saved_dictionary.pkl', 'rb') as f:
    loaded_dict = pickle.load(f)
print(len(loaded_dict))
print(*loaded_dict, sep = '\n')"""

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X


odometer_value  year_produced  engine_has_gas  engine_capacity  \
0              190000           2010               0              2.5   
1              290000           2002               0              3.0   
2              402000           2001               0              2.5   
3               10000           1999               0              3.0   
4              280000           2001               0              2.5   
...               ...            ...             ...              ...   
38526          290000           2000               0              3.5   
38527          321000           2004               0              2.2   
38528          777957           2000               0              3.5   
38529           20000           2001               0              2.0   
38530          297729           2000               0              2.4   

       has_warranty  is_exchangeable  number_of_photos  up_counter  feature_0  \
0                 0                0                 9          13          0   
1                 0                1                12          54          0   
2                 0                1                 4          72          0   
3                 0                1                 9          42          1   
4                 0                1                14           7          0   
...             ...              ...               ...         ...        ...   
38526             0                1                 5          85          0   
38527             0                1                 4          20          0   
38528             0                0                 3          63          0   
38529             0                1                 7         156          0   
38530             0                1                 4          73          0   

       feature_1  ...  body_type_sedan  body_type_suv  body_type_universal  \
0              1  ...                0              0                    1   
1              1  ...                0              0                    1   
2              1  ...                0              1                    0   
3              0  ...                1              0                    0   
4              1  ...                0              0                    1   
...          ...  ...              ...            ...                  ...   
38526          1  ...                1              0                    0   
38527          1  ...                0              0                    0   
38528          1  ...                1              0                    0   
38529          1  ...                0              0                    0   
38530          0  ...                0              0                    0   

       body_type_van  state_emergency  state_new  state_owned  drivetrain_all  \
0                  0                0          0            1               1   
1                  0                0          0            1               1   
2                  0                0          0            1               1   
3                  0                0          0            1               1   
4                  0                0          0            1               1   
...              ...              ...        ...          ...             ...   
38526              0                0          0            1               0   
38527              0                0          0            1               0   
38528              0                0          0            1               0   
38529              0                0          0            1               0   
38530              0                0          0            1               0   

       drivetrain_front  drivetrain_rear  
0                     0                0  
1                     0                0  
2                     0                0  
3                     0                0  
4                     0         

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

#Данные разделены на обучающую и тестовую подборку


((30824, 105), (30824,), (7707, 105), (7707,))

In [24]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression().fit(X_train, y_train)
lr.predict(X_test)

array([ 6762.436022  , 11762.10218111, -1051.58035629, ...,
       10385.73509513,  5997.99786495, 11322.93210687])

In [25]:
import numpy as np
from math import sqrt

def MAE(y_test, y_predict):
    return np.sum(abs(np.array(y_test)-np.array(y_predict)))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((np.array(y_test) - np.array(y_predict)) ** 2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((np.array(y_test) - np.array(y_predict)) / np.array(y_test)))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) * len(y_test) / (np.sum((np.array(y_test) - np.array(y_test).mean()) ** 2) ))

def maee(y_test, y_pred):
    return np.mean(abs(y_test-y_pred))

In [26]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

y_pred = lr.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')


MAE: 2004.9329401119903
MSE: 10103499.577797297
RMSE: 3178.6002544826706
MAPE: 0.6818255988218239
R^2: 0.7528028445304848


In [27]:
len(lr.coef_)
lr.coef_

array([-5.16824881e-03,  3.90338908e+02, -5.00538530e+02,  6.03097873e+02,
        1.14764039e+03, -1.68019917e+02,  6.92118111e+01, -5.39865040e-01,
        2.95367697e+02, -6.05236084e+02,  3.29049922e+02,  7.60250559e+02,
        2.52409745e+01,  2.63186747e+01,  1.02024477e+03,  1.16804407e+03,
        2.41674677e+00,  5.43717454e+01,  1.47646197e+00, -3.93626675e+01,
        4.28901922e+01,  1.92929241e+03, -2.40626991e+02,  1.99326419e+03,
        2.19271616e+03, -2.14073648e+03, -6.56459200e+01, -4.51105594e+03,
       -1.06957988e+03, -3.19808120e+02, -5.45287206e+02, -2.09085173e+03,
       -1.52960262e+03, -3.22313309e+02, -5.86368166e+02, -2.74783818e+01,
       -3.70303466e+03, -5.00269949e+03,  4.84639236e+02, -1.93921371e+02,
        4.30623015e+02,  3.17822730e+03,  6.59478799e+03, -4.74285478e+02,
       -4.37603386e+02, -3.73104335e+03, -6.01412874e+02,  1.86233533e+03,
        5.19185874e+03, -3.80868277e+03, -3.08472109e+02,  1.60413574e+02,
        2.52769378e+03,  

In [28]:
# L1
ridge = Ridge(alpha=0.9).fit(X_train, y_train)
y_pred = ridge.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
ridge.coef_

MAE: 2005.0210004747119
MSE: 10103488.564960713
RMSE: 3178.598522141592
MAPE: 0.6817654904614261
R^2: 0.7528031139759237


array([-5.17082705e-03,  3.90157643e+02, -4.72545049e+02,  6.05674901e+02,
        1.19198562e+03, -1.68153465e+02,  6.93298889e+01, -5.42038827e-01,
        2.96115705e+02, -6.05642669e+02,  3.30316424e+02,  7.59185673e+02,
        2.61562157e+01,  2.57647911e+01,  1.02033411e+03,  1.16902760e+03,
        3.95027524e+00,  5.40209490e+01,  1.47940491e+00, -3.93825823e+01,
        4.30832667e+01,  1.88950749e+03, -2.43044445e+02,  1.98577661e+03,
        2.17898199e+03, -2.08823658e+03, -7.17037460e+01, -4.42857685e+03,
       -1.06944884e+03, -3.25452824e+02, -5.47676772e+02, -2.05608691e+03,
       -1.52311451e+03, -3.27110201e+02, -5.86913338e+02, -3.15352136e+01,
       -3.63208419e+03, -4.85517451e+03,  4.79744878e+02, -1.95693043e+02,
        4.17335005e+02,  3.14066866e+03,  6.43616188e+03, -4.73332544e+02,
       -4.38821443e+02, -3.69999831e+03, -5.97568609e+02,  1.84544391e+03,
        5.15495243e+03, -3.72111639e+03, -2.94195720e+02,  1.56507001e+02,
        2.51431337e+03,  

In [29]:
# L2
lasso = Lasso(alpha=0.9).fit(X_train, y_train)
y_pred = lasso.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')

lasso.coef_

MAE: 2006.2657246249164
MSE: 10120614.481907656
RMSE: 3181.291323017692
MAPE: 0.6802141808766874
R^2: 0.7523841029271783


array([-5.18118464e-03,  3.89123260e+02, -1.91814443e+02,  6.31935039e+02,
        1.13741242e+03, -1.66056559e+02,  7.01370510e+01, -5.72213675e-01,
        2.91897546e+02, -6.13572803e+02,  3.40701834e+02,  7.49072817e+02,
        3.20205528e+01,  2.94996550e+01,  1.01940288e+03,  1.18050221e+03,
        1.47770084e+01,  4.69338608e+01,  1.48891193e+00, -3.91719527e+01,
        4.30178756e+01,  1.55573248e+03, -0.00000000e+00,  2.13221182e+03,
        2.27510810e+03, -1.12674444e+03,  0.00000000e+00, -3.73462695e+03,
       -7.95674816e+02, -7.31095082e+01, -3.41072018e+02, -1.36120438e+03,
       -1.16625545e+03, -3.87631511e+01, -3.34889636e+02,  1.40134629e+02,
       -2.93685313e+03, -3.83914793e+03,  6.38866503e+02, -0.00000000e+00,
        3.30449359e+02,  3.07535439e+03,  5.99361391e+03, -0.00000000e+00,
       -2.01462133e+02, -3.27888262e+03, -2.99300060e+01,  1.84730153e+03,
        5.18055087e+03, -2.85969531e+03, -0.00000000e+00,  3.12863606e+02,
        2.61905212e+03,  

In [30]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np


parameters = {'alpha': np.arange(0, 1, 0.1)}


# а теперь пробуем подобрать значение этого гиперпараметра с помощью GridSearchCV
# оборачиваем нашу модель в объект GridSearchCV, туда же передаем словарь с параметрами и стартуем обучение
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [31]:
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [32]:
data2=df

y = y_train.values.reshape(-1, 1)
X = X_train.values.reshape(-1, 105)

In [33]:
lr = LinearRegression().fit(X, y)
lr.coef_

array([[-5.16824881e-03,  3.90338908e+02, -5.00538530e+02,
         6.03097873e+02,  1.14764039e+03, -1.68019917e+02,
         6.92118111e+01, -5.39865040e-01,  2.95367697e+02,
        -6.05236084e+02,  3.29049922e+02,  7.60250559e+02,
         2.52409745e+01,  2.63186747e+01,  1.02024477e+03,
         1.16804407e+03,  2.41674677e+00,  5.43717454e+01,
         1.47646197e+00, -3.93626675e+01,  4.28901922e+01,
         1.92929241e+03, -2.40626991e+02,  1.99326419e+03,
         2.19271616e+03, -2.14073648e+03, -6.56459200e+01,
        -4.51105594e+03, -1.06957988e+03, -3.19808120e+02,
        -5.45287206e+02, -2.09085173e+03, -1.52960262e+03,
        -3.22313309e+02, -5.86368166e+02, -2.74783818e+01,
        -3.70303466e+03, -5.00269949e+03,  4.84639236e+02,
        -1.93921371e+02,  4.30623015e+02,  3.17822730e+03,
         6.59478799e+03, -4.74285478e+02, -4.37603386e+02,
        -3.73104335e+03, -6.01412874e+02,  1.86233533e+03,
         5.19185874e+03, -3.80868277e+03, -3.08472109e+0

In [34]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)  
# добавляем новые предикторы
X_p=pf.fit_transform(X_train) 
X_p
X_t = pf.fit_transform(X_test)

In [35]:
lr2 = LinearRegression().fit(X_p, y)
lr2.coef_

array([[-31596.45032662, -42795.15103546, -18459.01168781, ...,
         51698.63183034,      0.        ,  36495.64379238]])

In [36]:
X_d = X_p
y_d = lr2.coef_[0][2] + lr2.coef_[0][1]*X_d + lr2.coef_[0][0]*X_d**2
y_d



array([[-9.28506130e+04, -1.99220517e+15, -1.26597870e+11, ...,
        -9.28506130e+04, -1.84590117e+04, -1.84590117e+04],
       [-9.28506130e+04, -1.26386657e+15, -1.27231119e+11, ...,
        -9.28506130e+04, -1.84590117e+04, -1.84590117e+04],
       [-9.28506130e+04, -1.81681258e+15, -1.26977630e+11, ...,
        -1.84590117e+04, -1.84590117e+04, -1.84590117e+04],
       ...,
       [-9.28506130e+04, -1.46055512e+15, -1.26218679e+11, ...,
        -9.28506130e+04, -1.84590117e+04, -1.84590117e+04],
       [-9.28506130e+04, -1.49143576e+15, -1.27611827e+11, ...,
        -9.28506130e+04, -1.84590117e+04, -1.84590117e+04],
       [-9.28506130e+04, -3.87071495e+13, -1.24833178e+11, ...,
        -1.84590117e+04, -1.84590117e+04, -9.28506130e+04]])

In [37]:
# L1
ridge = Ridge(alpha=0.5).fit(X_p, y)
y_pred = ridge.predict(X_p)
#y_pred = y_d
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
ridge.coef_

MAE: 1212.3248308474376
MSE: 3854820.7364535946
RMSE: 1963.3697401288416
MAPE: 0.7019485542030898
R^2: 0.9069593430298175


array([[ 1.65006593e+00, -3.31789415e+00, -2.21683205e+04, ...,
         1.41192327e+04, -8.19934429e+00, -4.13935571e+03]])

In [ ]:
# L2
lasso = Lasso(alpha=0.5).fit(X_p, y)
y_pred = lasso.predict(X_p)
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
lasso.coef_

D:\user - wrs\sdfasf\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.305e+10, tolerance: 1.277e+08
  model = cd_fast.enet_coordinate_descent(


MAE: 193145127.92571282
