# Лабораторная работа 1. Введение в машинное обучение. Обучение с учителем. Задача регрессии

<b>Традиционное предупреждение для всех лабораторных работ:</b> перед обучением моделей необходимо выполнить предварительную обработку данных, которая <b>обязательно</b> включает в себя:
- заполнение пропущенных значений (рекомедуется логика заполнения пропусков на основе типа данных, которая использовалась в РГР по Практикуму);
- преобразование категориальных признаков в числовые (используйте one-hot кодирование или map; используйте знания с Практикума).

Предобработка может включать в себя другие действия, но выполнение описанных выше действий обязательно.

Сделайте это один раз и сохраните в отдельный csv файл, а потом его используйте.

<b>Выполните следующие задания:</b>
- загрузите датасет для регрессии, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (линейная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (полиномиальная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- вычислите значения метрик $R^2$, MAE, MSE, RMSE, MAPE для всех обученных моделей; выберите лучшую модель;
- самостоятельно реализуйте (желательно в виде класса) модель линейной регрессии с регуляризацией (можете выбрать L1 или L2);
- самостоятельно реализуйте вычисление всех используемых метрик (в виде функций, принимающих два аргумента);
- обучите вашу модель линейной регрессии на ваших данных; оцените качество с помощью реализованных вами метрик.

In [253]:
# пишите код здесь и в ячейках ниже
import pandas as pd
import numpy as np

#df = pd.read_csv('..\data\cars.csv')

#df.info()
#df.describe()

#df = df.replace({ True : 1 , False : 0 })

#s=pd.get_dummies(df)
#s.to_csv('..\data\one-hot_encoded_cars.csv', index=False)


#Проверка датасета на пустые значения

#missing_data = df.isnull()
#for column in missing_data.columns.values.tolist():
#    print(column)
#    print(missing_data[column].value_counts())
#    print(" ")
#df.isnull().sum()    
#df.info()


#Замена NaN значений в столбце объема двигателя

#vnn = df['engine_capacity'].dropna()
#df['engine_capacity'] = df['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))



"""
df = pd.read_csv('..\data\one-hot_encoded_cars.csv')

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X
"""




#Датасет предобработан: значения False/True заменены на 0/1;
#Выполнено one-hot кодирование; пустые значения в датафрейме заменены;
#Выделены целевой признак и предикторы


'\ndf = pd.read_csv(\'..\\data\\one-hot_encoded_cars.csv\')\n\ny = df["price_usd"]\nX = df.drop(["price_usd"], axis=1)\nX\n'

In [254]:
"""
ddf = pd.read_csv('..\data\cars.csv')
xxx = ddf.drop(columns = 'color')
xxx['longtitude']=np.zeros(38531)
xxx['latitude']=np.zeros(38531)
towndata = {
'мнд': np.float64(27.56152), 'мнш': np.float64(53.90454),
'год': np.float64(30.98785), 'гош': np.float64(52.44118),
'бд': np.float64(23.73405), 'бш': np.float64(52.09762),
'мд': np.float64(30.33136), 'мш': np.float64(53.90072),
'вд': np.float64(30.20162), 'вш': np.float64(55.18481),
'гд': np.float64(23.81313), 'гш': np.float64(53.66935)

}

#print(towndata["Миснк"][1])
for i in xxx['drivetrain']:
    if i == "front":
        i = int(0)
    if i == "rear":
        i = int(1)
    if i == "all":
        i = int(2)
print(xxx['location_region'].unique())
for i in range(len(xxx['location_region'])):
    
    #print(xxx['location_region'][i])
    
    if xxx['location_region'][i]=='Минская обл.':
        xxx['longtitude'][i]=towndata['мнд']
        xxx['latitude'][i]=towndata['мнш']
        
    if xxx['location_region'][i]=='Гомельская обл.':
        xxx['longtitude'][i]=towndata['год']
        xxx['latitude'][i]=towndata['гош']
        
    if xxx['location_region'][i]=='Брестская обл.':
        xxx['longtitude'][i]=towndata['бд']
        xxx['latitude'][i]=towndata['бш']
        
    if xxx['location_region'][i]=='Могилевская обл.':
        xxx['longtitude'][i]=towndata['мд']
        xxx['latitude'][i]=towndata['мш']
        
    if xxx['location_region'][i]=='Витебская обл.':
        xxx['longtitude'][i]=towndata['вд']
        xxx['latitude'][i]=towndata['вш']
        
    if xxx['location_region'][i]=='Гродненская обл.':
        xxx['longtitude'][i]=towndata['гд']
        xxx['latitude'][i]=towndata['гш']

#for i in range(len(xxx['location_region'])):
    #print(xxx['location_region'][i], xxx['latitude'][i], xxx['longtitude'][i])
xxx.info()




xxx = xxx.drop(columns = "location_region")
vnn = xxx['engine_capacity'].dropna()
xxx['engine_capacity'] = xxx['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))
xxx = xxx.replace({ True : 1 , False : 0 })
xxx = xxx.drop(columns = "model_name")
s=pd.get_dummies(xxx)
s.to_csv('..\data\workinset.csv', index=False)

"""
# False/True replaced with 0/1
# drivetrain replaced with 0/1/2 (front/rear/awd)
# region_location object type column replaced with two float64 type columns longtitude, lattitude
# color obj type column was dropped for less mem usage

# hope im not going to drop model or manufacturer column due to mem error :blessrng:

# model_name column was dropped :// saved 1100 columns
# other data was one-hot encoded


#df = pd.read_csv('..\data\one-hot_encoded_cars.csv')
df = pd.read_csv('..\data\workinset.csv')

"""ddf = pd.read_csv('..\data\cars.csv')
df["model_name"] = ddf["model_name"]
#print(*ddf['manufacturer_name'].unique())
print()
print()
#print(*df['model_name'].unique())
"""
"""foruniques['manufacturer_name'] = ddf['manufacturer_name']
foruniques['model_name']=df['model_name']
foruniques
"""

"""#print(*df['model_name'].unique())

ucars={}

uniquesm=df['model_name'].unique()
for i in range(len(uniquesm)):
    counter = 0
    
    for j in ddf['model_name']:
        
        #print(counter)
        if counter < 38533:
            #print(counter)
            if uniquesm[i]==j:
                #print(ddf['manufacturer_name'][counter], j)
                ucars[str(ddf['manufacturer_name'][counter] + ' ' + j)] = "Z"
                #print()
                #print()
                #print("promres", ucars)
        counter+=1
        
        
        
print("EXECUTED!!!")

import pickle 

with open('saved_dictionary.pkl', 'wb') as f:
    pickle.dump(ucars, f)
        
with open('saved_dictionary.pkl', 'rb') as f:
    loaded_dict = pickle.load(f)
print(len(loaded_dict))
print(*loaded_dict, sep = '\n')"""

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X


odometer_value  year_produced  engine_has_gas  engine_capacity  \
0              190000           2010               0              2.5   
1              290000           2002               0              3.0   
2              402000           2001               0              2.5   
3               10000           1999               0              3.0   
4              280000           2001               0              2.5   
...               ...            ...             ...              ...   
38526          290000           2000               0              3.5   
38527          321000           2004               0              2.2   
38528          777957           2000               0              3.5   
38529           20000           2001               0              2.0   
38530          297729           2000               0              2.4   

       has_warranty  is_exchangeable  number_of_photos  up_counter  feature_0  \
0                 0                0                 9          13          0   
1                 0                1                12          54          0   
2                 0                1                 4          72          0   
3                 0                1                 9          42          1   
4                 0                1                14           7          0   
...             ...              ...               ...         ...        ...   
38526             0                1                 5          85          0   
38527             0                1                 4          20          0   
38528             0                0                 3          63          0   
38529             0                1                 7         156          0   
38530             0                1                 4          73          0   

       feature_1  ...  body_type_sedan  body_type_suv  body_type_universal  \
0              1  ...                0              0                    1   
1              1  ...                0              0                    1   
2              1  ...                0              1                    0   
3              0  ...                1              0                    0   
4              1  ...                0              0                    1   
...          ...  ...              ...            ...                  ...   
38526          1  ...                1              0                    0   
38527          1  ...                0              0                    0   
38528          1  ...                1              0                    0   
38529          1  ...                0              0                    0   
38530          0  ...                0              0                    0   

       body_type_van  state_emergency  state_new  state_owned  drivetrain_all  \
0                  0                0          0            1               1   
1                  0                0          0            1               1   
2                  0                0          0            1               1   
3                  0                0          0            1               1   
4                  0                0          0            1               1   
...              ...              ...        ...          ...             ...   
38526              0                0          0            1               0   
38527              0                0          0            1               0   
38528              0                0          0            1               0   
38529              0                0          0            1               0   
38530              0                0          0            1               0   

       drivetrain_front  drivetrain_rear  
0                     0                0  
1                     0                0  
2                     0                0  
3                     0                0  
4                     0         

In [255]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

#Данные разделены на обучающую и тестовую подборку


((30824, 105), (30824,), (7707, 105), (7707,))

In [256]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression().fit(X_train, y_train)
lr.predict(X_test)

array([10268.39628491,  9736.77565046,  7464.83120389, ...,
        2852.31689158,   964.89979731,  5583.78582143])

In [257]:
import numpy as np
from math import sqrt

def MAE(y_test, y_predict):
    return np.sum(abs(np.array(y_test)-np.array(y_predict)))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((np.array(y_test) - np.array(y_predict)) ** 2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((np.array(y_test) - np.array(y_predict)) / np.array(y_test)))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) * len(y_test) / (np.sum((np.array(y_test) - np.array(y_test).mean()) ** 2) ))

def maee(y_test, y_pred):
    return np.mean(abs(y_test-y_pred))

In [258]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

y_pred = lr.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')


MAE: 1979.2109962760799
MSE: 9755966.761067431
RMSE: 3123.4542995003835
MAPE: 0.7881203075693488
R^2: 0.7567658015684527


In [259]:
len(lr.coef_)
lr.coef_

array([-5.35371041e-03,  3.87089793e+02, -4.82493404e+02,  6.19536799e+02,
        1.58514787e+03, -1.25606400e+02,  6.50445668e+01, -4.89932604e-01,
        3.18427891e+02, -5.68122481e+02,  3.44514484e+02,  8.09650314e+02,
        4.98919034e+00,  7.68345697e+01,  1.05618380e+03,  1.15013650e+03,
        1.47448506e+01,  2.52884678e+01,  1.76642211e+00, -2.94517769e+01,
        4.97626974e+01,  1.71607447e+03, -1.85544939e+02,  2.03441596e+03,
        2.26548002e+03, -1.72762898e+03, -5.23889198e+02, -4.61354222e+03,
       -9.45707734e+02, -2.65879759e+02, -5.92229576e+02, -2.00250857e+03,
       -1.70251279e+03, -4.01860576e+02, -5.44229988e+02, -7.57162230e+01,
       -3.70871036e+03, -5.04935910e+03,  5.59653880e+02, -2.75267639e+02,
        8.10327167e+02,  3.41734490e+03,  5.89815747e+03, -8.17680366e+02,
       -5.34550520e+02, -3.49673456e+03, -4.51985935e+02,  2.11163101e+03,
        5.03291134e+03, -3.84579439e+03, -2.64970842e+02,  2.24178031e+02,
        2.51680420e+03,  

In [260]:
# L1
ridge = Ridge(alpha=0.5).fit(X_train, y_train)
y_pred = ridge.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
ridge.coef_

MAE: 1979.188855075286
MSE: 9755989.690130457
RMSE: 3123.457969963812
MAPE: 0.8881963001209996
R^2: 0.7567652299047312


array([-5.35534149e-03,  3.86998527e+02, -4.66846009e+02,  6.21130955e+02,
        1.60607190e+03, -1.25613924e+02,  6.51096611e+01, -4.90256101e-01,
        3.18700238e+02, -5.68502181e+02,  3.45217886e+02,  8.08895973e+02,
        5.38871892e+00,  7.66219886e+01,  1.05625375e+03,  1.15066989e+03,
        1.56591574e+01,  2.49445924e+01,  1.76817017e+00, -2.94772866e+01,
        4.98747544e+01,  1.69729329e+03, -1.87334665e+02,  2.03010518e+03,
        2.25769068e+03, -1.70552510e+03, -5.20537919e+02, -4.56602331e+03,
       -9.46138464e+02, -2.69237815e+02, -5.93793233e+02, -1.98053647e+03,
       -1.69888384e+03, -4.04528697e+02, -5.44855266e+02, -7.81565407e+01,
       -3.66929485e+03, -4.95568227e+03,  5.56540989e+02, -2.76363411e+02,
        8.00841888e+02,  3.39505863e+03,  5.81366302e+03, -8.15632935e+02,
       -5.35395749e+02, -3.48179974e+03, -4.51273396e+02,  2.10088075e+03,
        5.01149190e+03, -3.79365357e+03, -2.53716635e+02,  2.21759227e+02,
        2.50921346e+03,  

In [261]:
# L2
lasso = Lasso(alpha=0.5).fit(X_train, y_train)
y_pred = lasso.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')

lasso.coef_

MAE: 1978.5518784827898
MSE: 9757417.043865971
RMSE: 3123.6864509527795
MAPE: 0.892742273371104
R^2: 0.7567296433503446


array([-5.35825479e-03,  3.86312685e+02, -1.48552006e+02,  6.36583568e+02,
        1.57455938e+03, -1.23736022e+02,  6.56625871e+01, -4.86708360e-01,
        3.12518824e+02, -5.71491564e+02,  3.51322106e+02,  8.00908007e+02,
        9.71087118e+00,  7.74586465e+01,  1.05503904e+03,  1.15776470e+03,
        2.23324176e+01,  2.22287290e+01,  1.76892503e+00, -2.96560855e+01,
        4.99701013e+01,  1.69331993e+03,  0.00000000e+00,  2.26370414e+03,
        2.46797411e+03, -1.03997184e+03, -0.00000000e+00, -4.02661064e+03,
       -6.41952021e+02, -0.00000000e+00, -3.29376704e+02, -1.38682087e+03,
       -1.35527045e+03, -9.91315140e+01, -2.57251261e+02,  1.67328150e+02,
       -3.12478382e+03, -4.17977928e+03,  7.95976031e+02, -0.00000000e+00,
        9.04054058e+02,  3.48866428e+03,  5.69194646e+03, -3.87450019e+02,
       -2.51693508e+02, -3.09877709e+03, -0.00000000e+00,  2.25539029e+03,
        5.17470867e+03, -3.14373529e+03,  0.00000000e+00,  4.59442897e+02,
        2.71965996e+03,  

In [262]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np


parameters = {'alpha': np.arange(0, 1, 0.1)}


# а теперь пробуем подобрать значение этого гиперпараметра с помощью GridSearchCV
# оборачиваем нашу модель в объект GridSearchCV, туда же передаем словарь с параметрами и стартуем обучение
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [263]:
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [264]:
data2=df

y = y_train.values.reshape(-1, 1)
X = X_train.values.reshape(-1, 105)

(30824, 105)

In [265]:
lr = LinearRegression().fit(X, y)
lr.coef_

array([[-5.35371041e-03,  3.87089793e+02, -4.82493404e+02,
         6.19536799e+02,  1.58514787e+03, -1.25606400e+02,
         6.50445668e+01, -4.89932604e-01,  3.18427891e+02,
        -5.68122481e+02,  3.44514484e+02,  8.09650314e+02,
         4.98919034e+00,  7.68345697e+01,  1.05618380e+03,
         1.15013650e+03,  1.47448506e+01,  2.52884678e+01,
         1.76642211e+00, -2.94517769e+01,  4.97626974e+01,
         1.71607447e+03, -1.85544939e+02,  2.03441596e+03,
         2.26548002e+03, -1.72762898e+03, -5.23889198e+02,
        -4.61354222e+03, -9.45707734e+02, -2.65879759e+02,
        -5.92229576e+02, -2.00250857e+03, -1.70251279e+03,
        -4.01860576e+02, -5.44229988e+02, -7.57162230e+01,
        -3.70871036e+03, -5.04935910e+03,  5.59653880e+02,
        -2.75267639e+02,  8.10327167e+02,  3.41734490e+03,
         5.89815747e+03, -8.17680366e+02, -5.34550520e+02,
        -3.49673456e+03, -4.51985935e+02,  2.11163101e+03,
         5.03291134e+03, -3.84579439e+03, -2.64970842e+0

In [266]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)  
# добавляем новые предикторы
X_p=pf.fit_transform(X) 
X_p

array([[1.00000e+00, 2.80000e+05, 2.00100e+03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 3.50000e+05, 1.98300e+03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 2.70000e+05, 1.99800e+03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [1.00000e+00, 2.84854e+05, 2.00400e+03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 2.97000e+05, 1.99700e+03, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.00000e+00, 1.14000e+05, 2.00800e+03, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00]])

In [267]:
lr2 = LinearRegression().fit(X_p, y)
lr2.coef_

array([[-78973.99138374, 145735.52060449, -15071.72857583, ...,
         24025.06546675,      0.        ,  31207.76993151]])

In [268]:
X_d = X_train.values.reshape(-1, 105)
y_d = lr2.coef_[0][2] + lr2.coef_[0][1]*X_d + lr2.coef_[0][0]*X_d**2
y_d

array([[-6.19152012e+15, -3.15920339e+11, -1.50717286e+04, ...,
        -1.50717286e+04,  5.16898006e+04, -1.50717286e+04],
       [-9.67426294e+15, -3.10259579e+11, -1.50717286e+04, ...,
        -1.50717286e+04,  5.16898006e+04, -1.50717286e+04],
       [-5.75716462e+15, -3.14973325e+11, -1.50717286e+04, ...,
        -1.50717286e+04,  5.16898006e+04, -1.50717286e+04],
       ...,
       [-6.40805040e+15, -3.16868774e+11, -1.50717286e+04, ...,
        -1.50717286e+04,  5.16898006e+04, -1.50717286e+04],
       [-6.96617352e+15, -3.14657970e+11, -1.50717286e+04, ...,
        -1.50717286e+04,  5.16898006e+04, -1.50717286e+04],
       [-1.02632938e+15, -3.18135566e+11, -1.50717286e+04, ...,
         5.16898006e+04, -1.50717286e+04, -1.50717286e+04]])