# Лабораторная работа 1. Введение в машинное обучение. Обучение с учителем. Задача регрессии

<b>Традиционное предупреждение для всех лабораторных работ:</b> перед обучением моделей необходимо выполнить предварительную обработку данных, которая <b>обязательно</b> включает в себя:
- заполнение пропущенных значений (рекомедуется логика заполнения пропусков на основе типа данных, которая использовалась в РГР по Практикуму);
- преобразование категориальных признаков в числовые (используйте one-hot кодирование или map; используйте знания с Практикума).

Предобработка может включать в себя другие действия, но выполнение описанных выше действий обязательно.

Сделайте это один раз и сохраните в отдельный csv файл, а потом его используйте.

<b>Выполните следующие задания:</b>
- загрузите датасет для регрессии, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (линейная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- решите задачу регрессии на ваших данных с использованием моделей sklearn (полиномиальная регрессия + L1, L2), для моделей с регуляризациями подберите гиперпараметр;
- вычислите значения метрик $R^2$, MAE, MSE, RMSE, MAPE для всех обученных моделей; выберите лучшую модель;
- самостоятельно реализуйте (желательно в виде класса) модель линейной регрессии с регуляризацией (можете выбрать L1 или L2);
- самостоятельно реализуйте вычисление всех используемых метрик (в виде функций, принимающих два аргумента);
- обучите вашу модель линейной регрессии на ваших данных; оцените качество с помощью реализованных вами метрик.

In [6]:
# пишите код здесь и в ячейках ниже
import pandas as pd
import numpy as np

#df = pd.read_csv('..\data\cars.csv')

#df.info()
#df.describe()

#df = df.replace({ True : 1 , False : 0 })

#s=pd.get_dummies(df)
#s.to_csv('..\data\one-hot_encoded_cars.csv', index=False)


#Проверка датасета на пустые значения

#missing_data = df.isnull()
#for column in missing_data.columns.values.tolist():
#    print(column)
#    print(missing_data[column].value_counts())
#    print(" ")
#df.isnull().sum()    
#df.info()


#Замена NaN значений в столбце объема двигателя

#vnn = df['engine_capacity'].dropna()
#df['engine_capacity'] = df['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))



"""
df = pd.read_csv('..\data\one-hot_encoded_cars.csv')

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X
"""




#Датасет предобработан: значения False/True заменены на 0/1;
#Выполнено one-hot кодирование; пустые значения в датафрейме заменены;
#Выделены целевой признак и предикторы


'\ndf = pd.read_csv(\'..\\data\\one-hot_encoded_cars.csv\')\n\ny = df["price_usd"]\nX = df.drop(["price_usd"], axis=1)\nX\n'

In [7]:
"""
ddf = pd.read_csv('..\data\cars.csv')
xxx = ddf.drop(columns = 'color')
xxx['longtitude']=np.zeros(38531)
xxx['latitude']=np.zeros(38531)
towndata = {
'мнд': np.float64(27.56152), 'мнш': np.float64(53.90454),
'год': np.float64(30.98785), 'гош': np.float64(52.44118),
'бд': np.float64(23.73405), 'бш': np.float64(52.09762),
'мд': np.float64(30.33136), 'мш': np.float64(53.90072),
'вд': np.float64(30.20162), 'вш': np.float64(55.18481),
'гд': np.float64(23.81313), 'гш': np.float64(53.66935)

}

#print(towndata["Минск"][1])
for i in xxx['drivetrain']:
    if i == "front":
        i = int(0)
    if i == "rear":
        i = int(1)
    if i == "all":
        i = int(2)
print(xxx['location_region'].unique())
for i in range(len(xxx['location_region'])):
    
    #print(xxx['location_region'][i])
    
    if xxx['location_region'][i]=='Минская обл.':
        xxx['longtitude'][i]=towndata['мнд']
        xxx['latitude'][i]=towndata['мнш']
        
    if xxx['location_region'][i]=='Гомельская обл.':
        xxx['longtitude'][i]=towndata['год']
        xxx['latitude'][i]=towndata['гош']
        
    if xxx['location_region'][i]=='Брестская обл.':
        xxx['longtitude'][i]=towndata['бд']
        xxx['latitude'][i]=towndata['бш']
        
    if xxx['location_region'][i]=='Могилевская обл.':
        xxx['longtitude'][i]=towndata['мд']
        xxx['latitude'][i]=towndata['мш']
        
    if xxx['location_region'][i]=='Витебская обл.':
        xxx['longtitude'][i]=towndata['вд']
        xxx['latitude'][i]=towndata['вш']
        
    if xxx['location_region'][i]=='Гродненская обл.':
        xxx['longtitude'][i]=towndata['гд']
        xxx['latitude'][i]=towndata['гш']

#for i in range(len(xxx['location_region'])):
    #print(xxx['location_region'][i], xxx['latitude'][i], xxx['longtitude'][i])
xxx.info()




xxx = xxx.drop(columns = "location_region")
vnn = xxx['engine_capacity'].dropna()
xxx['engine_capacity'] = xxx['engine_capacity'].fillna(round(sum(vnn)/len(vnn)))
xxx = xxx.replace({ True : 1 , False : 0 })
xxx = xxx.drop(columns = "model_name")
s=pd.get_dummies(xxx)
s.to_csv('..\data\workinset.csv', index=False)

"""
# False/True replaced with 0/1
# drivetrain replaced with 0/1/2 (front/rear/awd)
# region_location object type column replaced with two float64 type columns longtitude, lattitude
# color obj type column was dropped for less mem usage
# hope im not going to drop model or manufacturer column due to mem error :blessrng:
# model_name column was dropped :// saved 1100 columns
# other data was one-hot encoded


#df = pd.read_csv('..\data\one-hot_encoded_cars.csv')
df = pd.read_csv('..\data\workinset.csv')

y = df["price_usd"]
X = df.drop(["price_usd"], axis=1)
X


odometer_value  year_produced  engine_has_gas  engine_capacity  \
0              190000           2010               0              2.5   
1              290000           2002               0              3.0   
2              402000           2001               0              2.5   
3               10000           1999               0              3.0   
4              280000           2001               0              2.5   
...               ...            ...             ...              ...   
38526          290000           2000               0              3.5   
38527          321000           2004               0              2.2   
38528          777957           2000               0              3.5   
38529           20000           2001               0              2.0   
38530          297729           2000               0              2.4   

       has_warranty  is_exchangeable  number_of_photos  up_counter  feature_0  \
0                 0                0                 9          13          0   
1                 0                1                12          54          0   
2                 0                1                 4          72          0   
3                 0                1                 9          42          1   
4                 0                1                14           7          0   
...             ...              ...               ...         ...        ...   
38526             0                1                 5          85          0   
38527             0                1                 4          20          0   
38528             0                0                 3          63          0   
38529             0                1                 7         156          0   
38530             0                1                 4          73          0   

       feature_1  ...  body_type_sedan  body_type_suv  body_type_universal  \
0              1  ...                0              0                    1   
1              1  ...                0              0                    1   
2              1  ...                0              1                    0   
3              0  ...                1              0                    0   
4              1  ...                0              0                    1   
...          ...  ...              ...            ...                  ...   
38526          1  ...                1              0                    0   
38527          1  ...                0              0                    0   
38528          1  ...                1              0                    0   
38529          1  ...                0              0                    0   
38530          0  ...                0              0                    0   

       body_type_van  state_emergency  state_new  state_owned  drivetrain_all  \
0                  0                0          0            1               1   
1                  0                0          0            1               1   
2                  0                0          0            1               1   
3                  0                0          0            1               1   
4                  0                0          0            1               1   
...              ...              ...        ...          ...             ...   
38526              0                0          0            1               0   
38527              0                0          0            1               0   
38528              0                0          0            1               0   
38529              0                0          0            1               0   
38530              0                0          0            1               0   

       drivetrain_front  drivetrain_rear  
0                     0                0  
1                     0                0  
2                     0                0  
3                     0                0  
4                     0         

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

#Данные разделены на обучающую и тестовую подборку


((30824, 105), (30824,), (7707, 105), (7707,))

In [143]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression().fit(X_train, y_train)
lr.predict(X_test)

array([ 5836.39563372,  7446.28615327,  5717.91232714, ...,
        3078.021665  ,  2174.26086098, 10841.87720311])

In [10]:
import numpy as np
from math import sqrt

def MAE(y_test, y_predict):
    return np.sum(abs(np.array(y_test)-np.array(y_predict)))/len(y_test)

def MSE(y_test, y_predict):
    return np.sum((np.array(y_test) - np.array(y_predict)) ** 2) / len(y_test)

def RMSE(y_test, y_predict):
    return sqrt(MSE(y_test, y_predict))

def MAPE(y_test, y_predict):
    return np.mean(abs((np.array(y_test) - np.array(y_predict)) / np.array(y_test)))

def R2(y_test, y_predict):
    return 1 - (MSE(y_test, y_predict) * len(y_test) / (np.sum((np.array(y_test) - np.array(y_test).mean()) ** 2) ))

def maee(y_test, y_pred):
    return np.mean(abs(y_test-y_pred))

In [145]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt

y_pred = lr.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')


MAE: 2000.0001542667846
MSE: 10338904.560351523
RMSE: 3215.416700888319
MAPE: 0.6679285212662228
R^2: 0.7516225156771512


In [146]:
len(lr.coef_)
lr.coef_

array([-5.20027378e-03,  3.90068559e+02, -5.22382755e+02,  5.57921078e+02,
        9.36579169e+02, -1.62691811e+02,  6.70443175e+01, -9.38453998e-01,
        2.63930992e+02, -6.30825935e+02,  3.28670206e+02,  7.60435543e+02,
        3.77589426e+01,  4.36305065e+01,  1.04330760e+03,  1.16296094e+03,
       -6.66987125e+00,  1.76149910e+01,  1.63510507e+00, -3.45914566e+01,
        4.70395443e+01,  2.01619489e+03, -1.48715389e+02,  2.10781161e+03,
        2.28398440e+03, -1.68940782e+03, -6.70192393e+02, -4.57217988e+03,
       -1.22029068e+03, -2.30908243e+02, -4.78925517e+02, -1.97917185e+03,
       -1.72679593e+03, -2.30103852e+02, -4.82254907e+02,  1.74530074e+01,
       -3.64844927e+03, -5.01693961e+03,  5.98659687e+02, -2.75306438e+02,
        3.22773967e+02,  3.38791344e+03,  6.98116715e+03, -8.24521193e+02,
       -5.05583182e+02, -3.59227502e+03, -4.62545109e+02,  1.69114976e+03,
        5.00229865e+03, -4.05976270e+03, -1.37809006e+03,  2.32018794e+02,
        2.59326856e+03,  

In [147]:
# L1
ridge = Ridge(alpha=0.9).fit(X_train, y_train)
y_pred = ridge.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')
ridge.coef_

MAE: 1999.6727173664526
MSE: 10334688.688900713
RMSE: 3214.7610624898257
MAPE: 0.6675194098558966
R^2: 0.7517237959954932


array([-5.20260348e-03,  3.89891066e+02, -5.00226605e+02,  5.60329186e+02,
        9.80165121e+02, -1.62781697e+02,  6.71680757e+01, -9.35780074e-01,
        2.64312794e+02, -6.31553682e+02,  3.29884598e+02,  7.59170563e+02,
        3.83103919e+01,  4.34152574e+01,  1.04325599e+03,  1.16396590e+03,
       -4.70560725e+00,  1.69787270e+01,  1.63621411e+00, -3.46088900e+01,
        4.72728057e+01,  1.97367658e+03, -1.54065822e+02,  2.09810125e+03,
        2.26854785e+03, -1.65395706e+03, -6.58070158e+02, -4.48392345e+03,
       -1.22188609e+03, -2.38236009e+02, -4.83833164e+02, -1.94436676e+03,
       -1.72225897e+03, -2.37079383e+02, -4.85730460e+02,  1.09994898e+01,
       -3.58991546e+03, -4.87445012e+03,  5.91293365e+02, -2.79138165e+02,
        3.09316031e+02,  3.34580173e+03,  6.83473224e+03, -8.21011039e+02,
       -5.08615754e+02, -3.56529038e+03, -4.62896243e+02,  1.67387600e+03,
        4.96141099e+03, -3.96025522e+03, -1.29628399e+03,  2.25741699e+02,
        2.57786603e+03,  

In [148]:
# L2
lasso = Lasso(alpha=0.9).fit(X_train, y_train)
y_pred = lasso.predict(X_test)

print(f'MAE: {MAE(y_test, y_pred)}')
print(f'MSE: {MSE(y_test, y_pred)}')
print(f'RMSE: {RMSE(y_test, y_pred)}')
print(f'MAPE: {MAPE(y_test, y_pred)}')
print(f'R^2: {R2(y_test, y_pred)}')

lasso.coef_

MAE: 1999.0889374595959
MSE: 10319694.689331023
RMSE: 3212.4281609603386
MAPE: 0.663685943811194
R^2: 0.7520840055197535


array([-5.20601095e-03,  3.88665436e+02, -1.44732228e+02,  5.81432508e+02,
        9.09378999e+02, -1.59943498e+02,  6.80704729e+01, -9.51212560e-01,
        2.55952235e+02, -6.41446055e+02,  3.42163952e+02,  7.47673847e+02,
        3.95741157e+01,  4.56813372e+01,  1.04144535e+03,  1.17479074e+03,
        9.82425491e+00,  8.58155320e+00,  1.63569714e+00, -3.42780583e+01,
        4.79598126e+01,  1.67093585e+03,  0.00000000e+00,  2.25997136e+03,
        2.39234089e+03, -7.39846314e+02, -0.00000000e+00, -3.73422532e+03,
       -9.32181928e+02, -0.00000000e+00, -2.66573843e+02, -1.17361107e+03,
       -1.36568097e+03, -0.00000000e+00, -2.30843363e+02,  1.94248013e+02,
       -2.93357650e+03, -3.85898445e+03,  7.56386622e+02, -3.63696568e+01,
        2.51442230e+02,  3.30089144e+03,  6.50139235e+03, -2.96003150e+02,
       -2.57318510e+02, -3.12563149e+03, -0.00000000e+00,  1.70286882e+03,
        4.98692499e+03, -3.02484462e+03, -0.00000000e+00,  3.94761948e+02,
        2.70431131e+03,  

In [149]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import numpy as np


parameters = {'alpha': np.arange(0, 1, 0.1)}


# а теперь пробуем подобрать значение этого гиперпараметра с помощью GridSearchCV
# оборачиваем нашу модель в объект GridSearchCV, туда же передаем словарь с параметрами и стартуем обучение
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [150]:
ridge_optimal = GridSearchCV(Ridge(), parameters).fit(X_train, y_train)
# выводим оптимальные значения параметров
ridge_optimal.best_params_

{'alpha': 0.9}

In [155]:
data2=df

#y = y_train.values.reshape(-1, 1)
#X = X_train.values.reshape(-1, 105)

y = data2["price_usd"].values.reshape(-1, 1)
X = data2.drop(["price_usd"], axis=1).values.reshape(-1, 105)

In [156]:
lr = LinearRegression().fit(X, y)
lr.coef_

array([[-5.34553522e-03,  3.86499432e+02, -4.90054571e+02,
         5.85302071e+02,  1.40819644e+03, -1.77747192e+02,
         6.74018210e+01, -3.43384976e-01,  2.62627140e+02,
        -5.97378698e+02,  3.43086791e+02,  7.58765809e+02,
         2.38589589e+01,  5.35379514e+01,  1.09606604e+03,
         1.14745439e+03, -3.62723567e+00,  9.46570387e+00,
         1.55604776e+00, -3.50378867e+01,  4.75907723e+01,
         1.73215815e+03, -2.01850317e+02,  2.00096274e+03,
         2.28764953e+03, -1.84484399e+03, -4.67912757e+02,
        -4.53372297e+03, -1.08772563e+03, -2.74508310e+02,
        -5.56836276e+02, -2.17190290e+03, -1.62857223e+03,
        -3.40157775e+02, -5.61107440e+02, -6.72561739e+01,
        -3.77277984e+03, -5.07563335e+03,  5.27397424e+02,
        -2.69666561e+02,  7.17399445e+02,  3.34375509e+03,
         6.60042149e+03, -7.61097482e+02, -5.32516573e+02,
        -3.52382297e+03, -4.56753996e+02,  1.79286206e+03,
         5.00195544e+03, -3.90533841e+03,  9.38026282e+0

In [157]:
from sklearn.preprocessing import PolynomialFeatures
# создаем объект, который позволит расширить множество предикторов
pf = PolynomialFeatures(2)  
# добавляем новые предикторы
X_p=pf.fit_transform(X_train) 
#X_p
X_p=pf.fit_transform(X) 

#X_t = pf.fit_transform(X_test)

In [159]:
lr2 = LinearRegression().fit(X_p, y)
lr2.coef_
print(lr2.coef_[0][2])

-20710.915700435402


In [160]:
X_d = X_p
#y_d = lr2.coef_[0][2] + lr2.coef_[0][1]*X_d + lr2.coef_[0][0]*X_d**2
#y_d



In [161]:
# L1
ridge = Ridge(alpha=0.5).fit(X_p, y)
y_pred = ridge.predict(X_p)
#y_pred = y_d
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {R2(y, y_pred)}')
ridge.score(X_p, y)
#ridge.coef_

MAE: 1214.811525936857
MSE: 3868281.146342858
RMSE: 1966.7946375620556
MAPE: 0.6568579319472332
R^2: 0.9063825031055521


0.9063825031055521

In [162]:
# L2
lasso = Lasso(alpha=0.5).fit(X_p, y)
y_pred = lasso.predict(X_p)
print(f'MAE: {MAE(y, y_pred)}')
print(f'MSE: {MSE(y, y_pred)}')
print(f'RMSE: {RMSE(y, y_pred)}')
print(f'MAPE: {MAPE(y, y_pred)}')
print(f'R^2: {lasso.score(X_p, y)}')

#lasso.coef_

D:\user - wrs\sdfasf\ML\venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.170e+11, tolerance: 1.592e+08
  model = cd_fast.enet_coordinate_descent(


MAE: 241187835.51433894
MSE: 2949555725583.3623
RMSE: 1717427.0655790197
MAPE: 3.4593027989054854
R^2: 0.8604713251596773


In [91]:
import numpy as np


class LinReg:

    def __init__(self, lr = 0.001, n_iters=250):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            y_pred = np.dot(X, self.weights) + self.bias

            dw = (1/n_samples) * np.dot(X.T, (y_pred-y))
            db = (1/n_samples) * np.sum(y_pred-y)

            self.weights = self.weights - self.lr * dw
            self.bias = self.bias - self.lr * db

    def predict(self, X):
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred

In [92]:
#print(np.seterr(all: 'ignore'))
test = LinReg()
X_train.values.reshape(-1, 105)
X_train.values.reshape(-1, 105)
y_train.values.reshape(-1, 1)
test.fit(X_train, y_train)
preds = test.predict(X_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from math import sqrt
print(f'MAE: {mean_absolute_error(y_test, preds)}')
print(f'MSE: {mean_squared_error(y_test, preds)}')
print(f'RMSE: {sqrt(mean_squared_error(y_test, preds))}')
print(f'MAPE: {sqrt(mean_absolute_percentage_error(y_test, preds))}')
#print(f'R^2: {lr.score(X_test, y_test)}')


ValueError: Input contains NaN.